services:
  redis:
    image: redis:7-alpine
    # This is required to stay in RAM only.
    command: redis-server --save "" --appendonly no
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/latest/operate/rs/databases/memory-performance/eviction-policy/
    # --maxmemory 1gb --maxmemory-policy allkeys-lrulpine
    # This prevents the creation of an anonymous volume.
    tmpfs:
      - /data
    networks:
      - cryptgeon

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      # Size limit for a single note.
      SIZE_LIMIT: 4MiB
      LISTEN_ADDR: 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - cryptgeon

networks:
  cryptgeon:
    driver: bridge

    # Optional health checks
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/live/"]
    #   interval: 1m
    #   timeout: 3s
    #   retries: 2
    #   start_period: 5s